### ISSUE TITLE
Testing in indoor new dataset 

### ISSUE THREAD

**Issue by ArghyaChatterjee** [youmi-zym/CompletionFormer#10]
Hello,
I have an indoor (large hallway) dataset captured by intelrealsense camera attached to a robot publishing all the topics in ROS. So, I have extracted the rgb images (424 x 240) and rgb aligned depth images (424 x 240), and all are synced. Both of their frame ids are `camera_front/camera_color_optical_frame`. The total number of rgb and depth images are 1200 and all are in png file format. The camera info topic which carries the intrinsic parameters are producing the same message for the whole time. Here is the camera info topic : 

```
header: 
  seq: 49136
  stamp: 
    secs: 1582327384
    nsecs: 769735564
  frame_id: "camera_front/camera_color_optical_frame"
height: 240
width: 424
distortion_model: "plumb_bob"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [304.7262878417969, 0.0, 214.2415313720703, 0.0, 304.77935791015625, 121.70726013183594, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [304.7262878417969, 0.0, 214.2415313720703, 0.0, 0.0, 304.77935791015625, 121.70726013183594, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---
```
Here is a sample picture and corresponding depth image:
![rgb_1582327403292089386](https://github.com/youmi-zym/CompletionFormer/assets/28845357/6e4250a7-8298-475c-9b5c-7702d3b9d5c0)
![depth_1582327403365282353](https://github.com/youmi-zym/CompletionFormer/assets/28845357/b595d661-215c-4a3d-ae26-55a61cf371bd)

Now, my questions are:
1. How the calibration file.txt would look like for each set of pairs ? (should be constant for each set up to 1200, only one will be enough) 
2. Which inference file should I use ? (KITTI or NYU-V2)
3. Please provide the test script to run in this case (with appropriate patch width, patch height and maximum depth flags).

Thanks in advance.
